spring:
  port: 8000
  grpc-port: 9090
  # http.log-request-details: true
  
# logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

asr:
  whisper:
    url: http://192.168.1.105:9000

llm:
  ollama:
    url: http://192.168.1.105:11434

tts:
  open-tts:
    url: http://192.168.1.105:5500
